### PR TITLE
add option to query pods only on namespace

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/kubernetes-client.hkube/1)

### CODE REVIEW

**Review by nassiharel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/kubernetes-client.hkube/1)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @NassiHarel and @yehiyam)

___
*[lib/pods.js, line 5 at r1](https://reviewable.io/reviews/kube-hpc/kubernetes-client.hkube/1#-Lh__p5PEexXFCIYLXcz:-Lh__kL07nTGsueA3r6B:be1yb2s) ([raw file](https://github.com/kube-hpc/kubernetes-client.hkube/blob/5080eabf500814473e4530b3d36b58d7f70e6837/lib/pods.js#L5)):*
> ```JavaScript
> 
> class Pods extends Client {
>     async get({ podName, labelSelector }) {
> ```

I suggest to just add default = {} to the existing get function

async get({ podName, labelSelector } = {}) {
        return this._client.api.v1.namespaces(this._namespace).pods(podName).get({ qs: { labelSelector } });
 }

it('should get all in namespace', async () => {
         const res = await client.pods.get();
});

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/kubernetes-client.hkube/1)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[lib/pods.js, line 5 at r1](https://reviewable.io/reviews/kube-hpc/kubernetes-client.hkube/1#-Lh__p5PEexXFCIYLXcz:-Lha89QHB2Rgv3_Y5ma-:ba96r22) ([raw file](https://github.com/kube-hpc/kubernetes-client.hkube/blob/5080eabf500814473e4530b3d36b58d7f70e6837/lib/pods.js#L5)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

I suggest to just add default = {} to the existing get function

async get({ podName, labelSelector } = {}) {
        return this._client.api.v1.namespaces(this._namespace).pods(podName).get({ qs: { labelSelector } });
 }

it('should get all in namespace', async () => {
         const res = await client.pods.get();
});



</blockquote></details>

I think merging all() and get() makes the code less readable. The use case of get all, or get one pod is different

**Review by nassiharel — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/kubernetes-client.hkube/1)* status: all files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[lib/pods.js, line 5 at r1](https://reviewable.io/reviews/kube-hpc/kubernetes-client.hkube/1#-Lh__p5PEexXFCIYLXcz:-Lhd0GFW8Gypq22idOR-:b8f84s6) ([raw file](https://github.com/kube-hpc/kubernetes-client.hkube/blob/5080eabf500814473e4530b3d36b58d7f70e6837/lib/pods.js#L5)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

I think merging all() and get() makes the code less readable. The use case of get all, or get one pod is different
</blockquote></details>

But I don't like `if` in my code   ; -)
Maybe we should add an optional parameter `namespace`?
but this should be done in all functions...

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/kubernetes-client.hkube/1)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[lib/pods.js, line 5 at r1](https://reviewable.io/reviews/kube-hpc/kubernetes-client.hkube/1#-Lh__p5PEexXFCIYLXcz:-LhdLfr60ZU1jlZs44YR:b32w0x) ([raw file](https://github.com/kube-hpc/kubernetes-client.hkube/blob/5080eabf500814473e4530b3d36b58d7f70e6837/lib/pods.js#L5)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

But I don't like `if` in my code   ; -)
Maybe we should add an optional parameter `namespace`?
but this should be done in all functions...
</blockquote></details>

OK

**Review by nassiharel — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/kubernetes-client.hkube/1)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

**Review by nassiharel — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/kube-hpc/kubernetes-client.hkube/1#-:-LhdNiQ-AzwsV_5YK8xz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
